import type { Project } from '../../interfaces/Objects';

export const projectList: Project[] = [
    {
        id: 1,
        name: 'EduIA',
        description: 'Intelligent Education Support System.',
        imageURL: '/projects/EduIA.webp',
        projectURL: 'https://github.com/Davi-1903/EduIA',
        technologies: ['React', 'Flask', 'Tailwind', 'MySQL', 'AI', 'Docker'],
        team: [
            { id: 1, name: 'Ana Cecilya', url: 'https://github.com/cecilya1' },
            { id: 2, name: 'Ana Clara', url: 'https://github.com/anaclaraa1' },
            { id: 3, name: 'Maria das Graças', url: 'https://github.com/mgdantas1' },
            { id: 4, name: 'Miguel Tavares', url: 'https://github.com/migueltvrs13' },
        ],
    },
    {
        id: 2,
        name: 'API-Rust',
        description: 'User CRUD with Axum',
        imageURL: '/projects/API-Rust.webp',
        projectURL: 'https://github.com/Davi-1903/API-Rust',
        technologies: ['Rust'],
    },
    {
        id: 3,
        name: 'MediCloud',
        description: 'Medical clinic scheduling system for the POAS course',
        imageURL: '/projects/MediCloud.webp',
        projectURL: 'https://github.com/Davi-1903/MediCloud',
        technologies: ['React', 'FastAPI', 'Tailwind','MySQL'],
        team: [
            { id: 1, name: 'Ana Cecilya', url: 'https://github.com/cecilya1' },
            { id: 2, name: 'Ana Clara', url: 'https://github.com/anaclaraa1' },
            { id: 3, name: 'Maria das Graças', url: 'https://github.com/mgdantas1' },
        ],
    },
    {
        id: 4,
        name: 'Site-2M',
        description: 'Website for the InfoWeb 2M class',
        imageURL: '/projects/Site-2M.webp',
        projectURL: 'https://github.com/Davi-1903/Site-2M',
        technologies: ['React'],
    },
    {
        id: 5,
        name: 'BeeIdle',
        description: 'Terminal-based code editor',
        imageURL: '/projects/BeeIdle.webp',
        projectURL: 'https://github.com/Davi-1903/BeeIdle',
        technologies: ['Python'],
    },
    {
        id: 6,
        name: 'ToDoList',
        description: 'A simple to-do list with React that runs only in the browser',
        imageURL: '/projects/ToDoList.webp',
        projectURL: 'https://github.com/Davi-1903/ToDoList',
        technologies: ['React', 'Tailwind'],
    },
    {
        id: 7,
        name: 'Downloader',
        description: 'App for downloading videos and audio from YouTube',
        imageURL: '/projects/Downloader.webp',
        projectURL: 'https://github.com/Davi-1903/Downloader',
        technologies: ['Python'],
    },
    {
        id: 8,
        name: 'Pong-IA',
        description: 'Secund project made to study neural networks',
        imageURL: '/projects/Pong-IA.webp',
        projectURL: 'https://github.com/Davi-1903/Pong-IA',
        technologies: ['Python', 'AI'],
    },
    {
        id: 9,
        name: 'Usuários',
        description: 'Extremely simple login application to learn how to integrate Flask with React Router.',
        imageURL: '/projects/Usuarios.webp',
        projectURL: 'https://github.com/Davi-1903/Usuarios',
        technologies: ['React', 'Flask', 'Tailwind', 'MySQL', 'Docker'],
    },
    {
        id: 10,
        name: 'Flappy-Bird-IA',
        description: 'First project made to study neural networks',
        imageURL: '/projects/Flappy-Bird-IA.webp',
        projectURL: 'https://github.com/Davi-1903/Flappy-Bird-IA',
        technologies: ['PyGame', 'NumPy', 'AI'],
    },
    {
        id: 11,
        name: 'Expotec-2024',
        description: 'Game developed with pygame for technological exhibition.',
        imageURL: '/projects/Expotec-2024.webp',
        projectURL: 'https://github.com/Davi-1903/Expotec-2024',
        technologies: ['PyGame'],
        team: [
            { id: 1, name: 'Arthur Guilherme', url: 'https://github.com/ArthurGui004' },
            { id: 2, name: 'Pedro Lucas', url: 'https://github.com/Pepeulu' },
            { id: 3, name: 'Guilherme Medeiros', url: 'https://github.com/GuiMeCa162' },
        ],
    },
    {
        id: 12,
        name: 'ChatBot',
        description: 'Simple ChatBot with Flask and React',
        imageURL: '/projects/ChatBot.webp',
        projectURL: 'https://github.com/Davi-1903/ChatBot',
        technologies: ['React', 'Flask', 'AI'],
    },
    {
        id: 13,
        name: 'Dino-IA',
        description: 'Third project made to study neural networks',
        imageURL: '/projects/Dino-IA.webp',
        projectURL: 'https://github.com/Davi-1903/Dino-IA',
        technologies: ['PyGame', 'NumPy', 'AI'],
    },
    {
        id: 14,
        name: 'Termo',
        description: 'A game created on the terminal',
        imageURL: '/projects/Termo.webp',
        projectURL: 'https://github.com/Davi-1903/Termo',
        technologies: ['Python'],
    },
    {
        id: 15,
        name: 'CubeTime',
        description: 'Simple application to learn how to integrate Flask and React',
        imageURL: '/projects/CubeTime.webp',
        projectURL: 'https://github.com/Davi-1903/CubeTime',
        technologies: ['React', 'Flask', 'Tailwind', 'MySQL', 'Docker'],
    },
    {
        id: 16,
        name: 'Treino-Aguia',
        description: 'Attempt to teach a neural network to play the Expotec-2024 game',
        imageURL: '/projects/Treino-Aguia.webp',
        projectURL: 'https://github.com/Davi-1903/Treino-Aguia',
        technologies: ['PyGame', 'AI'],
    },
    {
        id: 17,
        name: 'GoWay',
        description: 'Web design project. Tourism blog.',
        imageURL: '/projects/GoWay.webp',
        projectURL: 'https://github.com/Davi-1903/GoWay',
        technologies: ['HTML', 'CSS', 'JavaScript'],
        team: [
            { id: 1, name: 'Ana Cecilya', url: 'https://github.com/cecilya1' },
            { id: 2, name: 'Ana Clara', url: 'https://github.com/anaclaraa1' },
            { id: 3, name: 'Maria das Graças', url: 'https://github.com/mgdantas1' },
        ],
    },
];
